Add event init to initialize repo hooks
Summary:
Add event init to initialize repo hooks

Hooks are written to files in a temp dir, then copied over to the sparse repo's .git/hooks.
The hooks are simply `focus event <hook-name>`, which will call the respective logic from within focus.

Test Plan:
`focus test --workspace`

Also manual testing shows that when merge happens, the post-merge logic in focus gets called. (Which is a todo right now)
```
thread 'main' panicked at 'not yet implemented: not implemented', focus/commands/src/cli/main.rs:1029:43
```

Reviewers: O57517 focus:/!

JIRA Issues: PFD-131

Differential Revision: https://phabricator.twitter.biz/D905675