[focus] Raise error on non-deterministic content hashing
Summary: To catch these errors before they start causing correctness issues in the wild, elevate this situation to an error.

Test Plan:
Observe that it exposes the non-deterministic content hashing at present:

```
$ cargo run --release -- -C ~/workspace/source-focus4 index clear
$ cargo run --release -- -C ~/workspace/source-focus4 sync
...
2022-05-17T22:49:42.065282Z focus_internals::index::object_database: Non-deterministic dependency hashing key=BazelPackage(Label("@antlr3_runtime//jar:downloaded.jar")) old_value=PackageInfo { deps: {BazelPackage(Label("@xmlpull_xmlpull_1.1.3.1//file:downloaded"))} } new_value=PackageInfo { deps: {} } hash=ContentHash(9c5dcf563333857697429b55f4a2c09f0dfaa7f1)
2022-05-17T22:49:42.117288Z focus_internals::operation::util: Failed computing the new sparse profile: Sync failed
2022-05-17T22:49:42.117384Z focus_util::backed_up_file: Restoring backed up file self.backup_path="/Users/wkhan/workspace/source-focus4/.git/info/sparse-checkout.backup" self.original_path="/Users/wkhan/workspace/source-focus4/.git/info/sparse-checkout"
Error: Sync failed

Caused by:
    Non-deterministic dependency hashing
```

Reviewers: #focus, wilhelm

JIRA Issues: PFD-148

Differential Revision: https://phabricator.twitter.biz/D895818