build: propagate `twttr` feature flag
Specifying an individual package for builds could fail because the `twttr` feature wasn't propagated all the way through, such as for

```
$ cargo test -F twttr testing::sync::sync_layer_manipulation -p focus-operations --lib
error[E0599]: no method named `get_ti_context` found for struct `MutexGuard<'_, Underlying>` in the current scope
   --> focus/operations/src/testing/sync.rs:359:10
    |
359 |         .get_ti_context()
    |          ^^^^^^^^^^^^^^ method not found in `MutexGuard<'_, Underlying>`

error[E0599]: no method named `get_ti_context` found for struct `MutexGuard<'_, Underlying>` in the current scope
   --> focus/operations/src/testing/sync.rs:369:10
    |
369 |         .get_ti_context()
    |          ^^^^^^^^^^^^^^ method not found in `MutexGuard<'_, Underlying>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `focus-operations` due to 2 previous errors
```